### ISSUE TITLE
Feature Request:  Remove messages for channels that are no longer online

### ISSUE THREAD

**Issue by dopeghoti** [bsquidwrd/Live-Bot#24]
Would it be possible to have the bot monitor its channel and check links to streaming platforms (say, every five minutes), checking the status of the stream, and purge the message if the channel is offline?

**Comment by bsquidwrd** [comment]
To me, this sounds like #9 which I know I'm not the best at getting these things done, but I am working on a full rewrite of the bot and will be easier to implement things like this.

**Comment by dopeghoti** [comment]
Quite so, I didn't see that FR when I looked.  I look forward to future developments!
